/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.esciencenet.forms;

import com.esciencenet.models.DomainFileModel;
import com.esciencenet.models.PeerGroupModel;
import com.esciencenet.semanticmanager.SemanticManager;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Tadeu
 */
public class FDomainOntology extends javax.swing.JDialog {

    private List<DomainFileModel> lstDomainFileModels;
    
    /**
     * Creates new form FDomainOntology
     */
    public FDomainOntology(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        
        if (System.getProperty("os.name").toLowerCase().equals("linux")){
            this.setType(Type.UTILITY);
        }else{
            this.setType(Type.POPUP);
        }
        
        lstDomainFileModels = SemanticManager.getInstance().obterDomainFiles("");
        
        this.preencherCombo(cbmGrupos);            
    }

    private void preencherCombo(JComboBox comboBox){
        
        ArrayList<PeerGroupModel> lstPeerGroupModel = SemanticManager.getInstance().obterGrupos();
        
        //crio o modelo de items da combobox
        DefaultComboBoxModel cmdModel = new DefaultComboBoxModel();        

        //percorro a lista de grupos encontrados
        for (PeerGroupModel peerGroup : lstPeerGroupModel){
            //seto o elemento no modelo
            cmdModel.addElement(peerGroup.getGroupName());
        }       
        
        //seto o modelo e o indice do item na combobox
        comboBox.setModel(cmdModel);        
        comboBox.setSelectedItem(SemanticManager.getInstance().getInterestManager().getGrupoSelecionado().getGroupName());        
    }
    
    public void limparTabela(){
        
        DefaultTableModel defaultTableModel = (DefaultTableModel) tblArquivos.getModel();
                
        while (defaultTableModel.getRowCount() != 0){         
            defaultTableModel.removeRow(0);            
        }        
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form
     * Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ppmTabela = new javax.swing.JPopupMenu();
        actExcluir = new javax.swing.JMenuItem();
        fileChoser = new javax.swing.JFileChooser();
        pnlMain = new javax.swing.JPanel();
        pnlFiltro = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbmGrupos = new javax.swing.JComboBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblArquivos = new javax.swing.JTable();
        pnlFooter = new javax.swing.JPanel();
        btnFechar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();

        actExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/trash-icon.png"))); // NOI18N
        actExcluir.setText("Delete");
        actExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actExcluirActionPerformed(evt);
            }
        });
        ppmTabela.add(actExcluir);

        fileChoser.setAcceptAllFileFilterUsed(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Domain Ontology");

        pnlFiltro.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Group filter");

        cbmGrupos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbmGruposItemStateChanged(evt);
            }
        });
        cbmGrupos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmGruposActionPerformed(evt);
            }
        });
        cbmGrupos.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cbmGruposPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout pnlFiltroLayout = new javax.swing.GroupLayout(pnlFiltro);
        pnlFiltro.setLayout(pnlFiltroLayout);
        pnlFiltroLayout.setHorizontalGroup(
            pnlFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFiltroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbmGrupos, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlFiltroLayout.setVerticalGroup(
            pnlFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFiltroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbmGrupos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblArquivos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "OWL File"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblArquivos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tblArquivos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblArquivosMouseReleased(evt);
            }
        });
        jScrollPane3.setViewportView(tblArquivos);
        tblArquivos.getColumnModel().getColumn(0).setMinWidth(200);
        tblArquivos.getColumnModel().getColumn(0).setPreferredWidth(200);
        tblArquivos.getColumnModel().getColumn(0).setMaxWidth(200);
        tblArquivos.getColumnModel().getColumn(1).setMinWidth(650);
        tblArquivos.getColumnModel().getColumn(1).setPreferredWidth(650);

        pnlFooter.setBackground(new java.awt.Color(192, 192, 192));

        btnFechar.setBackground(new java.awt.Color(192, 192, 192));
        btnFechar.setText("Close");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        btnExcluir.setBackground(new java.awt.Color(192, 192, 192));
        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/trash-icon.png"))); // NOI18N
        btnExcluir.setText("Delete");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlFooterLayout = new javax.swing.GroupLayout(pnlFooter);
        pnlFooter.setLayout(pnlFooterLayout);
        pnlFooterLayout.setHorizontalGroup(
            pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFooterLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlFooterLayout.setVerticalGroup(
            pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFooterLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFechar)
                    .addComponent(btnExcluir))
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFiltro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 877, Short.MAX_VALUE)
            .addComponent(pnlFooter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addComponent(pnlFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlFooter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(895, 409));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnFecharActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
                
        String domainName = tblArquivos.getModel().getValueAt(tblArquivos.getSelectedRow(), 0).toString();
        String fileName = tblArquivos.getModel().getValueAt(tblArquivos.getSelectedRow(), 1).toString();
        
        if (JOptionPane.showConfirmDialog(this, "Do you really want to delete the domain "+ domainName +"?", "e-ScienceNet", 
            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.OK_OPTION){

            if (!SemanticManager.getInstance().removerDomainInOWL(domainName)){
                JOptionPane.showMessageDialog(this, "Wasn't possible to remove the domain in PeerOntology.", "e-ScienceNet", JOptionPane.ERROR_MESSAGE);
            }else{
                File fileOWL = new File(fileName);
                if (fileOWL.exists()){
                    fileOWL.delete();
                }

                this.removeDomain(domainName);

                if (cbmGrupos.getSelectedItem().toString().equals("")){
                    this.exibirDominios();
                }else{
                    exbirDominiosSobreFiltro(cbmGrupos.getSelectedItem().toString());
                }    
            }
        }
            
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void removeDomain(String domainName){
        
        for(DomainFileModel domainFileModel : lstDomainFileModels){
            
            if (domainFileModel.getDomainName().equals(domainName)){
                lstDomainFileModels.remove(domainFileModel);
                break;
            }
        }
    }
    
    private void cbmGruposItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbmGruposItemStateChanged

    }//GEN-LAST:event_cbmGruposItemStateChanged

    private void cbmGruposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmGruposActionPerformed
        
        if (cbmGrupos.getSelectedItem().toString().equals("")){
            this.exibirDominios();
        }else{
            exbirDominiosSobreFiltro(cbmGrupos.getSelectedItem().toString());
        }      
    }//GEN-LAST:event_cbmGruposActionPerformed

    private void cbmGruposPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cbmGruposPropertyChange

    }//GEN-LAST:event_cbmGruposPropertyChange

    private void tblArquivosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblArquivosMouseReleased
        if ((tblArquivos.getSelectedRow() >= 0) && (evt.isPopupTrigger())){
            ppmTabela.show(tblArquivos, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_tblArquivosMouseReleased

    private void actExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actExcluirActionPerformed
        this.btnExcluirActionPerformed(evt);
    }//GEN-LAST:event_actExcluirActionPerformed

    private void exbirDominiosSobreFiltro(String filtro){
      
        limparTabela();
        
        DefaultTableModel defaultTableModel = (DefaultTableModel) tblArquivos.getModel();
        
        for (DomainFileModel domain : lstDomainFileModels){
        
            if (domain.getGroup().getGroupName().equals(filtro)){
                Object[] linha = {domain.getDomainName(),                               
                                  domain.getDomainOWLFile()};

                defaultTableModel.addRow(linha);
            }
        }           
    }
    
    private void exibirDominios(){       
        
        limparTabela();
        
        DefaultTableModel defaultTableModel = (DefaultTableModel) tblArquivos.getModel();
        
        for (DomainFileModel domain : lstDomainFileModels){
        
            Object[] linha = {domain.getDomainName(),                               
                              domain.getDomainOWLFile()};
            
            defaultTableModel.addRow(linha);
        }        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem actExcluir;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnFechar;
    private javax.swing.JComboBox cbmGrupos;
    private javax.swing.JFileChooser fileChoser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel pnlFiltro;
    private javax.swing.JPanel pnlFooter;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPopupMenu ppmTabela;
    private javax.swing.JTable tblArquivos;
    // End of variables declaration//GEN-END:variables
}
