/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.esciencenet.forms;

import com.esciencenet.interestmanager.InterestManager;
import com.esciencenet.models.FindDomainFileModel;
import com.esciencenet.semanticmanager.OntologyFilter;
import com.esciencenet.semanticmanager.SemanticManager;
import com.esciencenet.utils.EScienceNetUtils;
import com.thoughtworks.xstream.XStream;
import com.thoughtworks.xstream.io.xml.DomDriver;
import java.io.File;
import java.net.MalformedURLException;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Tadeu
 */
public class FIncludeNewDomain extends javax.swing.JDialog {

    private String xml;
    
    /**
     * Creates new form FIncludeNewDomain
     */
    public FIncludeNewDomain(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form
     * Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChoser = new javax.swing.JFileChooser();
        pnlFiltro = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbmGrupos = new javax.swing.JComboBox();
        pnlFooter = new javax.swing.JPanel();
        btnFechar = new javax.swing.JButton();
        btnFechar1 = new javax.swing.JButton();
        lblURL = new javax.swing.JLabel();
        edtOWL = new javax.swing.JTextField();
        btnFolder = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Include a New Domain");
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        pnlFiltro.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Group filter");

        cbmGrupos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbmGruposItemStateChanged(evt);
            }
        });
        cbmGrupos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmGruposActionPerformed(evt);
            }
        });
        cbmGrupos.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cbmGruposPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout pnlFiltroLayout = new javax.swing.GroupLayout(pnlFiltro);
        pnlFiltro.setLayout(pnlFiltroLayout);
        pnlFiltroLayout.setHorizontalGroup(
            pnlFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFiltroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbmGrupos, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(433, Short.MAX_VALUE))
        );
        pnlFiltroLayout.setVerticalGroup(
            pnlFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFiltroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbmGrupos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlFooter.setBackground(new java.awt.Color(192, 192, 192));

        btnFechar.setBackground(new java.awt.Color(192, 192, 192));
        btnFechar.setText("Close");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        btnFechar1.setBackground(new java.awt.Color(192, 192, 192));
        btnFechar1.setText("Include");
        btnFechar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFechar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlFooterLayout = new javax.swing.GroupLayout(pnlFooter);
        pnlFooter.setLayout(pnlFooterLayout);
        pnlFooterLayout.setHorizontalGroup(
            pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFooterLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFechar1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlFooterLayout.setVerticalGroup(
            pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFooterLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFechar)
                    .addComponent(btnFechar1))
                .addContainerGap())
        );

        lblURL.setText("Ontology File");

        edtOWL.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                edtOWLFocusLost(evt);
            }
        });

        btnFolder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/directory-accept-icon.png"))); // NOI18N
        btnFolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFolderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFiltro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlFooter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblURL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edtOWL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFolder, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblURL)
                        .addComponent(edtOWL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnFolder, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlFooter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(372, 372, 372))
        );

        setSize(new java.awt.Dimension(735, 171));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cbmGruposItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbmGruposItemStateChanged

    }//GEN-LAST:event_cbmGruposItemStateChanged

    private void cbmGruposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmGruposActionPerformed

    }//GEN-LAST:event_cbmGruposActionPerformed

    private void cbmGruposPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cbmGruposPropertyChange

    }//GEN-LAST:event_cbmGruposPropertyChange

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnFecharActionPerformed

    private void edtOWLFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edtOWLFocusLost

    }//GEN-LAST:event_edtOWLFocusLost

    private void btnFolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFolderActionPerformed
        OntologyFilter filter = new OntologyFilter("Web Ontology Language (*.owl)", "owl");
        fileChoser.addChoosableFileFilter(filter);

        if (fileChoser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION){            
            edtOWL.setText(fileChoser.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_btnFolderActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        
        DefaultComboBoxModel cmdModel = (DefaultComboBoxModel) cbmGrupos.getModel();
        cmdModel.addElement(SemanticManager.getInstance().getInterestManager().getGrupoSelecionado().getGroupName());
        cbmGrupos.setModel(cmdModel);      
        this.edtOWL.setText("");
    }//GEN-LAST:event_formComponentShown

    private void btnFechar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFechar1ActionPerformed
        
        String fileName = this.verifyExistentsDomains();
        
        fileName = SemanticManager.getInstance().getDirOntology() + File.separator + SemanticManager.DOMAINS_OWL_DIR + File.separator + fileName;
        
        fileName = fileName.replace(File.separator + File.separator, File.separator);
        
        if(! edtOWL.getText().equals(fileName)){
            if(!EScienceNetUtils.copyLocalFiles(edtOWL.getText(), fileName)){
                JOptionPane.showMessageDialog(this, "Wasn't possible to copy you ontology.", ".: e-ScienceNet :.", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        
        SemanticManager.getInstance().getInterestManager().processNewDomain(fileName);
        
        this.setVisible(false);
    }//GEN-LAST:event_btnFechar1ActionPerformed

    private String verifyExistentsDomains(){        
        try{
            File owlDomain = new File(edtOWL.getText());
            
            XStream xstream = new XStream(new DomDriver());
            List<FindDomainFileModel> lstFileDomainModel = (List<FindDomainFileModel>) xstream.fromXML(this.xml);
            
            Integer version = 0;
            String nomeDominio = "";
            
            for(FindDomainFileModel domainFileModel : lstFileDomainModel){
                if(domainFileModel.getNome().contains(owlDomain.getName().replace(".owl", ""))){
                    version++;
                }
            }
            
            if(version == 0){
                nomeDominio = owlDomain.getName().replace(".owl", "") + ".owl";
            }else{
                nomeDominio = owlDomain.getName().replace(".owl", "") + "__" + version.toString() + ".owl";
            }
            
            return nomeDominio;
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e, ".: e-ScienceNet :.", JOptionPane.ERROR_MESSAGE);
            return "";
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnFechar1;
    private javax.swing.JButton btnFolder;
    private javax.swing.JComboBox cbmGrupos;
    private javax.swing.JTextField edtOWL;
    private javax.swing.JFileChooser fileChoser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblURL;
    private javax.swing.JPanel pnlFiltro;
    private javax.swing.JPanel pnlFooter;
    // End of variables declaration//GEN-END:variables

    /**
     * @param xml the xml to set
     */
    public void setXml(String xml) {
        
        xml = xml.substring(xml.lastIndexOf("#") + 1);
        
        this.xml = xml;
    }
}
