/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.esciencenet.forms;

import com.esciencenet.semanticmanager.SemanticManager;
import java.awt.Frame;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import juniorvs.virtualdir.Peers;

/**
 *
 * @author Tadeu
 */
public class FPeerConectados extends javax.swing.JDialog {

        
    public class JTableRenderer extends DefaultTableCellRenderer  {    
    
        @Override
        protected void setValue(Object value){    

            if (value instanceof ImageIcon){    

                if (value != null){    
                    ImageIcon d = (ImageIcon) value;    
                    setIcon(d);    
                } else{    
                    setText("");    
                    setIcon(null);  
                    this.setFont(this.getFont().deriveFont(16));
                }    

            } else {    
                super.setValue(value);    
            }    

            this.setHorizontalAlignment(CENTER);            
        }
    }
    
    /**
     * Creates new form FPeerConectados
     */   
    public FPeerConectados(java.awt.Frame parent, boolean modal, Peers peers){
     
        super(parent, modal);
        initComponents();
        
        this.setLocationRelativeTo(null);
                
        inserirPeers(peers);
    }

    private void inserirPeers(Peers peers){
                
        TableColumnModel ColumnModel = tblPeers.getColumnModel();    
        JTableRenderer renderer = new JTableRenderer();    
        ColumnModel.getColumn(0).setCellRenderer(renderer);    
        ColumnModel.getColumn(2).setCellRenderer(renderer);
        
        DefaultTableModel defaultTableModel = (DefaultTableModel) tblPeers.getModel();

        Icon peer = new ImageIcon(getClass().getResource("/images/homepeer.png"));   
        Icon content = new ImageIcon(getClass().getResource("/images/homepeer.png"));

        Object[] linha = {peer, SemanticManager.getInstance().getNomePeer().concat(" - [LOCAL PEER]"), content};

        defaultTableModel.addRow(linha);
        
        for (int i = 0; i < peers.getQtdPeers(); i++){
        
            peer = new ImageIcon(getClass().getResource("/images/netpeer.png"));
            
            content = (peers.getPeer(i).getQtdAnuncioConteudo() > 0) ? (new ImageIcon(getClass().getResource("/images/nocontent.png"))) : 
                                                                            (new ImageIcon(getClass().getResource("/images/content.png")));
            
            Object[] peerInfo = {peer, peers.getPeer(i).getNome(), content};
            
            defaultTableModel.addRow(peerInfo);
        }
        
        tblPeers.setRowHeight(30);
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form
     * Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFooter = new javax.swing.JPanel();
        btnFechar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblPeers = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Connected Peers");

        pnlFooter.setBackground(new java.awt.Color(192, 192, 192));

        btnFechar.setBackground(new java.awt.Color(192, 192, 192));
        btnFechar.setText("Close");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlFooterLayout = new javax.swing.GroupLayout(pnlFooter);
        pnlFooter.setLayout(pnlFooterLayout);
        pnlFooterLayout.setHorizontalGroup(
            pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFooterLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlFooterLayout.setVerticalGroup(
            pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFooterLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFechar)
                .addContainerGap())
        );

        tblPeers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "Name", "Content"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPeers.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tblPeers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblPeersMouseReleased(evt);
            }
        });
        jScrollPane3.setViewportView(tblPeers);
        tblPeers.getColumnModel().getColumn(0).setMinWidth(35);
        tblPeers.getColumnModel().getColumn(0).setPreferredWidth(35);
        tblPeers.getColumnModel().getColumn(0).setMaxWidth(35);
        tblPeers.getColumnModel().getColumn(2).setMinWidth(60);
        tblPeers.getColumnModel().getColumn(2).setPreferredWidth(60);
        tblPeers.getColumnModel().getColumn(2).setMaxWidth(60);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFooter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlFooter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getAccessibleContext().setAccessibleName("frmPeersConectadis");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnFecharActionPerformed

    private void tblPeersMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPeersMouseReleased

    }//GEN-LAST:event_tblPeersMouseReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFechar;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel pnlFooter;
    private javax.swing.JTable tblPeers;
    // End of variables declaration//GEN-END:variables

    private FPeerConectados(Frame parent, boolean modal) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
