package com.esciencenet.forms;

import javax.swing.JOptionPane;
import juniorvs.virtualdir.GerenciaProcura;

/**
 * Formulário responsável pelo download dos arquivos entre os nós
 * 
 * @author Tadeu Classe
 */
public class FrmDownload extends javax.swing.JDialog {

    //atributos da classe
    private GerenciaProcura gerenciaProcura;
    
    /**
     * Método construtor do fomrulário de download de arquivos
     * 
     * @param parent formulário pai para o download
     * @param modal escolha se o formulário terá comportamento modal ou não
     * @param gerenciaProcura objeto do gerente de busca de arquivos na rede
     */
    public FrmDownload(java.awt.Frame parent, boolean modal, GerenciaProcura gerenciaProcura) {
        //passo os parâmetros para a classe
        super(parent, modal);
        
        //seto o formulário no centro da tela
        setLocationRelativeTo(null);
        //retiro as barras da janela
        setUndecorated(true); 
        //inicializo os componentes
        initComponents();    
        
        if (System.getProperty("os.name").toLowerCase().equals("linux")){
            this.setType(Type.UTILITY);
        }else{
            this.setType(Type.POPUP);
        }
        
        //passo o gerente de procura para o formulário
        this.gerenciaProcura = gerenciaProcura;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form
     * Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblArquivo = new javax.swing.JLabel();
        pgbDownload = new javax.swing.JProgressBar();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Download...");
        setResizable(false);

        lblArquivo.setText("...");

        pgbDownload.setForeground(new java.awt.Color(102, 54, 219));
        pgbDownload.setStringPainted(true);

        btnCancelar.setText("Cancelar");
        btnCancelar.setActionCommand("Cancel");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pgbDownload, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 3, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblArquivo)
                .addGap(14, 14, 14)
                .addComponent(pgbDownload, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("frmDownload");

        setSize(new java.awt.Dimension(405, 114));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        //mostro a janela de questionamento de cancelamento do download
        if (JOptionPane.showConfirmDialog(this, "Would you like really to cancel the file download?", ".: e-ScienceNet :.", JOptionPane.YES_NO_OPTION, 
                                      JOptionPane.QUESTION_MESSAGE, (new javax.swing.ImageIcon(getClass().getResource("/images/question.png")))) == 0){         
            //cancelo o download no objeto de gerencia de procura
            gerenciaProcura.cancelar();
            //seto a janela como não visivel
            this.setVisible(false);
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel lblArquivo;
    private javax.swing.JProgressBar pgbDownload;
    // End of variables declaration//GEN-END:variables

    /**
     * Insiro os valores para exibição do andamento do download
     * 
     * @param perncent porcentagem do progresso do download
     * @param descricao descrição do arquivo que está sendo baixado
     */
    public void setValue(int perncent, String descricao){
        //exibo o nome do arquivo que está sendo baixado
        lblArquivo.setText("Download: " + descricao);
        //seto a porcentagem na barra de progresso
        pgbDownload.setValue(perncent);
    }
}
