/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.esciencenet.forms;

import java.util.ArrayList;
import com.esciencenet.models.*;
import java.awt.Font;
import java.awt.Frame;
import java.util.concurrent.Semaphore;
import javax.swing.DefaultComboBoxModel;
import com.esciencenet.semanticmanager.*;

/**
 *
 * @author Tadeu Classe
 */
public class FrmGrupos extends javax.swing.JDialog {

    private ArrayList<PeerGroupModel> peerGroupLst;
    
    /**
     * Creates new form FrmGrupos
     */
    public FrmGrupos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);       
        initComponents();
        
        //coloco a posição do formulário para o centro da tela
        setLocationRelativeTo(null);  
    }
    
    public FrmGrupos(Frame parent, boolean modal, ArrayList<PeerGroupModel> peerGroupLst){
        super(parent, modal);       
        initComponents();
        this.peerGroupLst = peerGroupLst;
        
        //crio os grupos na combobox
        criarModeloComboGrupos();
        
        //coloco a posição do formulário para o centro da tela
        setLocationRelativeTo(null);   
    }

    private void criarModeloComboGrupos(){
        
        DefaultComboBoxModel cmdModel = new DefaultComboBoxModel();        
        
        for (PeerGroupModel peerGroup : peerGroupLst){
            cmdModel.addElement(peerGroup.getGroupName());
        }
        
        cmdModel.insertElementAt("Nenhum Grupo", 0);        
        cmbGrupos.setModel(cmdModel);        
        cmbGrupos.setSelectedIndex(0);
    }
    
    private PeerGroupModel obterPeerGrupo(String nomeGrupo){
        
        for (PeerGroupModel peerGroup : peerGroupLst){
            
            if(peerGroup.getGroupName().equals(nomeGrupo)){
                return peerGroup;
            }            
        }
        
        return null;
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form
     * Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFooter = new javax.swing.JPanel();
        btnOK = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        pnlMain = new javax.swing.JPanel();
        gpbGrupos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbGrupos = new javax.swing.JComboBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        mmoInfo = new javax.swing.JTextPane();
        btnDeleteGrupo = new javax.swing.JButton();
        btnNovoGrupo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Grupos e-ScienceNet");
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);

        pnlFooter.setBackground(new java.awt.Color(192, 192, 192));

        btnOK.setBackground(new java.awt.Color(192, 192, 192));
        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(192, 192, 192));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlFooterLayout = new javax.swing.GroupLayout(pnlFooter);
        pnlFooter.setLayout(pnlFooterLayout);
        pnlFooterLayout.setHorizontalGroup(
            pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFooterLayout.createSequentialGroup()
                .addContainerGap(236, Short.MAX_VALUE)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlFooterLayout.setVerticalGroup(
            pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFooterLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOK)
                    .addComponent(btnCancelar))
                .addContainerGap())
        );

        pnlMain.setLayout(null);

        gpbGrupos.setBorder(javax.swing.BorderFactory.createTitledBorder(" Grupos Disponíveis "));
        gpbGrupos.setLayout(null);

        jLabel1.setText("Informações");
        gpbGrupos.add(jLabel1);
        jLabel1.setBounds(10, 50, 418, 16);

        cmbGrupos.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cmbGruposPropertyChange(evt);
            }
        });
        gpbGrupos.add(cmbGrupos);
        cmbGrupos.setBounds(10, 20, 410, 22);

        mmoInfo.setEditable(false);
        jScrollPane3.setViewportView(mmoInfo);

        gpbGrupos.add(jScrollPane3);
        jScrollPane3.setBounds(10, 70, 410, 130);

        pnlMain.add(gpbGrupos);
        gpbGrupos.setBounds(10, 10, 430, 210);

        btnDeleteGrupo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/deleteGroup.png"))); // NOI18N
        btnDeleteGrupo.setText("Excluir Grupo");
        btnDeleteGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteGrupoActionPerformed(evt);
            }
        });
        pnlMain.add(btnDeleteGrupo);
        btnDeleteGrupo.setBounds(170, 225, 150, 30);

        btnNovoGrupo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/addGroup.png"))); // NOI18N
        btnNovoGrupo.setText("Novo Grupo");
        pnlMain.add(btnNovoGrupo);
        btnNovoGrupo.setBounds(10, 225, 150, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFooter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlFooter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-458)/2, (screenSize.height-361)/2, 458, 361);
    }// </editor-fold>//GEN-END:initComponents

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        
        //fecho a tela de grupos
        this.fechar();
    }//GEN-LAST:event_btnOKActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        //fecho a tela de grupos
        this.fechar();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void cmbGruposPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cmbGruposPropertyChange
        
        PeerGroupModel peerGroup = obterPeerGrupo(cmbGrupos.getSelectedItem().toString());
        
        if (peerGroup != null){
            
            String html = "<b>Nome do Grupo:</b> " + peerGroup.getGroupName() + "<br>" +
                          "<b>Área:</b> " + peerGroup.getGroupArea() + "<br>" + 
                          "<b>Autor:</b> " + peerGroup.getGroupCreator() + "<br>" +
                          "<b>Identificador:</b> " + peerGroup.getGroupID() + "<br><hr>"+
                          "<b>Descrição:</b><br> " + peerGroup.getGroupDescription();
            
            mmoInfo.setContentType("text/html");
            mmoInfo.setText(html);
        }else{
            mmoInfo.setText("");
        }
    }//GEN-LAST:event_cmbGruposPropertyChange

    private void btnDeleteGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteGrupoActionPerformed
        
        if (cmbGrupos.getSelectedIndex() != 0){
            String nomeGrupo = cmbGrupos.getSelectedItem().toString();
            SemanticManager.getInstance().removerGrupoOWL(nomeGrupo);            
            peerGroupLst.remove(obterPeerGrupo(nomeGrupo));
            criarModeloComboGrupos();
        }        
    }//GEN-LAST:event_btnDeleteGrupoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnDeleteGrupo;
    private javax.swing.JButton btnNovoGrupo;
    private javax.swing.JButton btnOK;
    private javax.swing.JComboBox cmbGrupos;
    private javax.swing.JPanel gpbGrupos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextPane mmoInfo;
    private javax.swing.JPanel pnlFooter;
    private javax.swing.JPanel pnlMain;
    // End of variables declaration//GEN-END:variables

    private void fechar(){
        setVisible(false);
    }
    
}
