/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.esciencenet.forms;

import com.esciencenet.utils.EScienceNetUtils;
import com.esciencenet.models.*;
import com.esciencenet.semanticmanager.*;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import sun.net.www.MimeEntry;
import sun.net.www.MimeTable;
import juniorvs.virtualdir.ext.*;

/**
 *
 * @author Tadeu Classe
 */
public class FrmIncluirArquivo extends javax.swing.JDialog {

    private SemanticManager semanticManager;
        
    /**
     * Creates new form FrmIncluirArquivo
     */
    public FrmIncluirArquivo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        
        initComponents();
        
        if (System.getProperty("os.name").toLowerCase().equals("linux")){
            this.setType(Type.UTILITY);
        }else{
            this.setType(Type.POPUP);
        }
        
        setLocationRelativeTo(null);
    }
    
    public FrmIncluirArquivo(java.awt.Frame parent, boolean modal, SemanticManager semanticManager) {
        super(parent, modal);
        
        initComponents();
        
        if (System.getProperty("os.name").toLowerCase().equals("linux")){
            this.setType(Type.UTILITY);
        }else{
            this.setType(Type.POPUP);
        }
        
        setLocationRelativeTo(null);
        
        this.semanticManager = semanticManager;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form
     * Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFooter = new javax.swing.JPanel();
        btnOK = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        pnlMain = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        edtArquivo = new javax.swing.JTextField();
        btnDiretorio = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        edtTamanho = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        edtData = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        edtExtensao = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        edtTipoArquivo = new javax.swing.JTextField();
        btnTipoArquivo = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        edtDescricao = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        edtNome = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Include Files");
        setResizable(false);

        pnlFooter.setBackground(new java.awt.Color(192, 192, 192));

        btnOK.setBackground(new java.awt.Color(192, 192, 192));
        btnOK.setText("Save");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(192, 192, 192));
        btnCancelar.setText("Cancel");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlFooterLayout = new javax.swing.GroupLayout(pnlFooter);
        pnlFooter.setLayout(pnlFooterLayout);
        pnlFooterLayout.setHorizontalGroup(
            pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFooterLayout.createSequentialGroup()
                .addContainerGap(459, Short.MAX_VALUE)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlFooterLayout.setVerticalGroup(
            pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFooterLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOK)
                    .addComponent(btnCancelar))
                .addContainerGap())
        );

        jLabel1.setText("File Path");

        btnDiretorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/directory-accept-icon.png"))); // NOI18N
        btnDiretorio.setText("Path");
        btnDiretorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiretorioActionPerformed(evt);
            }
        });

        jLabel2.setText("Size");

        edtTamanho.setEditable(false);
        edtTamanho.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel3.setText("KB");

        jLabel4.setText("Creation Date");

        edtData.setEditable(false);
        edtData.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel5.setText("Extension");

        edtExtensao.setEditable(false);

        jLabel6.setText("File Type");

        edtTipoArquivo.setEditable(false);

        btnTipoArquivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/type.png"))); // NOI18N
        btnTipoArquivo.setToolTipText("Alterar tipo de arquivo");
        btnTipoArquivo.setEnabled(false);
        btnTipoArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTipoArquivoActionPerformed(evt);
            }
        });

        jLabel7.setText("Description");

        edtDescricao.setColumns(20);
        edtDescricao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        edtDescricao.setLineWrap(true);
        edtDescricao.setRows(5);
        edtDescricao.setWrapStyleWord(true);
        jScrollPane1.setViewportView(edtDescricao);

        jLabel8.setText("File Name");

        edtNome.setEditable(false);

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(edtNome)
                            .addGroup(pnlMainLayout.createSequentialGroup()
                                .addComponent(edtArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDiretorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(pnlMainLayout.createSequentialGroup()
                                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlMainLayout.createSequentialGroup()
                                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(pnlMainLayout.createSequentialGroup()
                                                .addComponent(edtTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel3))
                                            .addComponent(jLabel2))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(edtData, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(edtExtensao, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(pnlMainLayout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addComponent(edtTipoArquivo)))
                                    .addGroup(pnlMainLayout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnTipoArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1))
                        .addContainerGap())
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel7))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edtArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDiretorio, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(edtTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(edtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edtExtensao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edtTipoArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8))
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnTipoArquivo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(edtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(167, 167, 167))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlFooter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnlMain, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlFooter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getAccessibleContext().setAccessibleName("frmIncludeFiles");

        setSize(new java.awt.Dimension(664, 387));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed

        FileModel fileModel = recuperarInformacoesComponentes();        

        if (semanticManager.gravarArquivoInOWL(fileModel)){                
            SemanticManager.getInstance().getDataManager().processarDownloadRequest(fileModel.getName() + fileModel.getExtension());
            
            JOptionPane.showConfirmDialog(this, "File inserted with success!", ".: e-ScienceNet :.", JOptionPane.DEFAULT_OPTION, 
                                          JOptionPane.INFORMATION_MESSAGE, (new javax.swing.ImageIcon(getClass().getResource("/images/information.png"))));
            
            this.setVisible(false);
        }
    }//GEN-LAST:event_btnOKActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnDiretorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiretorioActionPerformed
        File arquivo = exibirFileDiagora();
        
        if (arquivo != null){                            
            edtArquivo.setText(arquivo.getAbsolutePath());
            
            FileModel fileModel = this.obterInformacoesArquivo(arquivo);
            this.inserirInformacoesComponentes(fileModel);
        }
    }//GEN-LAST:event_btnDiretorioActionPerformed

    private void btnTipoArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTipoArquivoActionPerformed
        
        String tipoArquivo = JOptionPane.showInputDialog(this, "Insert the file type:", "File type");
        
        if (!tipoArquivo.equals("")){
            edtTipoArquivo.setText(tipoArquivo);
        }
        
        btnTipoArquivo.setEnabled(false);
    }//GEN-LAST:event_btnTipoArquivoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnDiretorio;
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnTipoArquivo;
    private javax.swing.JTextField edtArquivo;
    private javax.swing.JTextField edtData;
    private javax.swing.JTextArea edtDescricao;
    private javax.swing.JTextField edtExtensao;
    private javax.swing.JTextField edtNome;
    private javax.swing.JTextField edtTamanho;
    private javax.swing.JTextField edtTipoArquivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlFooter;
    private javax.swing.JPanel pnlMain;
    // End of variables declaration//GEN-END:variables

    private void inserirInformacoesComponentes(FileModel fileModel){
        
        edtNome.setText(fileModel.getName());
        edtData.setText(fileModel.getDate());
        edtExtensao.setText(fileModel.getExtension());
        edtTamanho.setText(Double.toString(fileModel.getSize()));
        
        if (!fileModel.getType().equals("")){
            edtTipoArquivo.setText(fileModel.getType());
        }else{
            btnTipoArquivo.setEnabled(true);
        }                
    }
    
    private FileModel recuperarInformacoesComponentes(){
        try{
            FileModel fileModel = new FileModel();
            
            fileModel.setName(EScienceNetUtils.RemoveSpecialCharacters(edtNome.getText()));
            fileModel.setDate(edtData.getText());
            fileModel.setDescription(edtDescricao.getText().equals("") ? "No Description" : EScienceNetUtils.RemoveSpecialCharacters(edtDescricao.getText()));
            fileModel.setExtension(edtExtensao.getText());
            fileModel.setPath(edtArquivo.getText().replace(fileModel.getName(), "").replace(fileModel.getExtension(), ""));
            fileModel.setSize(Double.parseDouble(edtTamanho.getText()));
            fileModel.setType(EScienceNetUtils.RemoveSpecialCharacters(edtTipoArquivo.getText()));
            
            fileModel.setPeerGroup(semanticManager.getInterestManager().getGrupoSelecionado());            
            fileModel.setPeerName(semanticManager.getNomePeer());
            
            return fileModel;
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e, ".: e-ScienceNet :.", JOptionPane.ERROR_MESSAGE);
            return null;
        }
    }
    
    private File exibirFileDiagora(){
        try{
            JFileChooser fc = new JFileChooser();
            fc.setMultiSelectionEnabled(false);
            fc.setDialogTitle("Inserting file in e-ScienceNet");
            fc.showOpenDialog(null);
            
            return fc.getSelectedFile();
        }catch (Exception e){
            System.out.println(e.getMessage());
            return null;
        }
    }
    
    private FileModel obterInformacoesArquivo(File arquivo){      
        try{
            FileModel fileModel = new FileModel();            
            fileModel.setSize(arquivo.length() / 1024);
            fileModel.setPath(arquivo.getParent());
            fileModel.setExtension(arquivo.getName().substring(arquivo.getName().lastIndexOf("."), arquivo.getName().length()));
            fileModel.setName(arquivo.getName().replace(fileModel.getExtension(), ""));

            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            fileModel.setDate(sdf.format(arquivo.lastModified()));

            MimeTable mimeTable = MimeTable.getDefaultTable();
            MimeEntry mimeEntry = mimeTable.findByFileName(arquivo.getName());
            fileModel.setType(mimeEntry == null ? "" : mimeEntry.getDescription());

            return fileModel;
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e, ".: e-ScienceNet :.", JOptionPane.ERROR_MESSAGE);
            return null;
        }
    }
}
