/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.esciencenet.forms;

import java.awt.FileDialog;
import java.io.File;
import juniorvs.virtualdir.ConteudoRemoto;
import juniorvs.virtualdir.GerenciaProcura;
import net.jxta.instantp2p.util.PreferenceReader;
import net.jxta.share.ContentAdvertisement;
import net.jxta.share.MimeInfo;

/**
 *
 * @author Tadeu Classe
 */
public class FrmSalvarRecurso extends javax.swing.JDialog {

    private ContentAdvertisement adv;
    private String diretorioPreferencia;
    private GerenciaProcura gerenciaProcura;
    private ConteudoRemoto conteudoRemoto;
    private String name;
    private String fileName;
    
    /**
     * Creates new form FrmSalvarRecurso
     */
    public FrmSalvarRecurso(java.awt.Frame parent, boolean modal) {
        super(parent, modal);        
        initComponents();
        
        if (System.getProperty("os.name").toLowerCase().equals("linux")){
            this.setType(Type.UTILITY);
        }else{
            this.setType(Type.POPUP);
        }
        
        setLocationRelativeTo(null);
    }
    
    public FrmSalvarRecurso(java.awt.Frame parent, boolean modal, String diretorioPreferencial, GerenciaProcura gerenciaProcura,
                            ConteudoRemoto conteudoRemoto, ContentAdvertisement adv, String name) {
        super(parent, modal);
        
        initComponents();
        
        if (System.getProperty("os.name").toLowerCase().equals("linux")){
            this.setType(Type.UTILITY);
        }else{
            this.setType(Type.POPUP);
        }
        
        this.diretorioPreferencia = diretorioPreferencial;
        this.gerenciaProcura = gerenciaProcura;
        this.conteudoRemoto = conteudoRemoto;
        
        setLocationRelativeTo(null);
        this.setResult(adv, name);
        
        try {
            if (fileName != null){
                PreferenceReader prefs = PreferenceReader.getInstance();
                String dir = (new File(fileName)).getParent();
                prefs.setProperty(getClass().getName() + ConteudoRemoto.DIRETORIO_PREFERENCIA, dir);
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form
     * Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pnlFooter = new javax.swing.JPanel();
        btnOK = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        edtArquivo = new javax.swing.JTextField();
        btnDiretorio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Save...");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setText("Path");

        pnlFooter.setBackground(new java.awt.Color(192, 192, 192));

        btnOK.setBackground(new java.awt.Color(192, 192, 192));
        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(192, 192, 192));
        btnCancelar.setText("Cancel");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlFooterLayout = new javax.swing.GroupLayout(pnlFooter);
        pnlFooter.setLayout(pnlFooterLayout);
        pnlFooterLayout.setHorizontalGroup(
            pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFooterLayout.createSequentialGroup()
                .addContainerGap(616, Short.MAX_VALUE)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlFooterLayout.setVerticalGroup(
            pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFooterLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOK)
                    .addComponent(btnCancelar))
                .addContainerGap())
        );

        btnDiretorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/directory-accept-icon.png"))); // NOI18N
        btnDiretorio.setText("Path");
        btnDiretorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiretorioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(edtArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 681, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDiretorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlFooter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edtArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDiretorio, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlFooter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getAccessibleContext().setAccessibleName("");

        setSize(new java.awt.Dimension(819, 145));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        fileName = null;
        if (edtArquivo.getText().equals("")) {
                return;
        }
        this.setVisible(false);
        fileName = edtArquivo.getText();
        gerenciaProcura.recuperaConteudo(adv, fileName, conteudoRemoto);
    }//GEN-LAST:event_btnOKActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnDiretorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiretorioActionPerformed
        FileDialog fd = new FileDialog(this, "Salvar Conteúdo", FileDialog.SAVE);
        String cwd = diretorioPreferencia;
        fd.setFile(name);
        fd.setDirectory(cwd);
        fd.show();
        setEnabled(true);
        
        if (fd.getDirectory() != null && fd.getFile() != null) {
            fileName = fd.getDirectory() + fd.getFile();
            edtArquivo.setText(fileName);
        }
    }//GEN-LAST:event_btnDiretorioActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.setVisible(false);
    }//GEN-LAST:event_formWindowClosing

    public void setResult(ContentAdvertisement adv, String name) {
        this.name = name;
        String cwd = diretorioPreferencia + "copiados" + File.separator + name;
        edtArquivo.setText(cwd);
        this.adv = adv;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnDiretorio;
    private javax.swing.JButton btnOK;
    private javax.swing.JTextField edtArquivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel pnlFooter;
    // End of variables declaration//GEN-END:variables
}
