/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.esciencenet.forms;

import com.esciencenet.utils.EScienceNetUtils;
import java.io.File;
import java.io.FileWriter;
import javax.swing.JOptionPane;

/**
 *
 * @author Tadeu Classe
 */
public class FViewWFResult extends javax.swing.JDialog {

    private String fileName;
    
    /**
     * Creates new form FViewWFResult
     */
    public FViewWFResult(java.awt.Frame parent, boolean modal, String fileName) {
        super(parent, modal);
        initComponents();
        this.fileName = fileName;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFooter = new javax.swing.JPanel();
        btnFechar = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        cbkEdition = new javax.swing.JCheckBox();
        cbkWordWrap = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        edtResults = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("View Workflow Result");
        setType(java.awt.Window.Type.UTILITY);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        pnlFooter.setBackground(new java.awt.Color(192, 192, 192));

        btnFechar.setBackground(new java.awt.Color(192, 192, 192));
        btnFechar.setText("Close");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        btnSave.setBackground(new java.awt.Color(192, 192, 192));
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save-as-icon.png"))); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        cbkEdition.setBackground(new java.awt.Color(192, 192, 192));
        cbkEdition.setText("Edition Allowed");
        cbkEdition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbkEditionActionPerformed(evt);
            }
        });

        cbkWordWrap.setBackground(new java.awt.Color(192, 192, 192));
        cbkWordWrap.setText("Line wrap");
        cbkWordWrap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbkWordWrapActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlFooterLayout = new javax.swing.GroupLayout(pnlFooter);
        pnlFooter.setLayout(pnlFooterLayout);
        pnlFooterLayout.setHorizontalGroup(
            pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFooterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbkEdition)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbkWordWrap)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 583, Short.MAX_VALUE)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlFooterLayout.setVerticalGroup(
            pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFooterLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFechar)
                    .addComponent(btnSave)
                    .addComponent(cbkEdition)
                    .addComponent(cbkWordWrap))
                .addContainerGap())
        );

        edtResults.setEditable(false);
        edtResults.setColumns(20);
        edtResults.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        edtResults.setRows(5);
        jScrollPane1.setViewportView(edtResults);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFooter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlFooter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setSize(new java.awt.Dimension(1013, 590));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnFecharActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        try{
            File file = new File(fileName);
            if(file.exists()){
                
                file.delete();
                file.createNewFile();
                
                if(file.exists()){
                    try (FileWriter fw = new FileWriter(file)) {
                        fw.write(EScienceNetUtils.encodeBase64(edtResults.getText()));
                        JOptionPane.showMessageDialog(null, "The file was save with success!", ".: e-ScienceNet :.", JOptionPane.INFORMATION_MESSAGE);
                    }
                }
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void cbkWordWrapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbkWordWrapActionPerformed
        edtResults.setLineWrap(cbkWordWrap.isSelected());
    }//GEN-LAST:event_cbkWordWrapActionPerformed

    private void cbkEditionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbkEditionActionPerformed
        edtResults.setEditable(cbkEdition.isSelected());
    }//GEN-LAST:event_cbkEditionActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        
        try{
            File file = new File(this.fileName);
            if(!file.exists()){
                throw new Exception("The file don't exists.");
            }
            
            String contenct = EScienceNetUtils.readFileToString(file, false);
            
            edtResults.setText(EScienceNetUtils.decodeBase64(contenct));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage(), ".: e-ScienceNet :.", JOptionPane.ERROR_MESSAGE);
            this.setVisible(false);
        }        
    }//GEN-LAST:event_formComponentShown

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnSave;
    private javax.swing.JCheckBox cbkEdition;
    private javax.swing.JCheckBox cbkWordWrap;
    private javax.swing.JTextArea edtResults;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlFooter;
    // End of variables declaration//GEN-END:variables
}
